orders = {
    "1001": {"status": "pending", "items": ["laptop", "mouse"], "date": "2025-05-20"},
    "1002": {"status": "shipped", "items": ["jacket"], "date": "2025-05-18"},
    "1003": {"status": "delivered", "items": ["monitor", "keyboard"], "date": "2025-05-15"},
    "1004": {"status": "pending", "items": ["smartphone", "case"], "date": "2025-05-21"},
    "1005": {"status": "shipped", "items": ["headphones", "charger"], "date": "2025-05-17"},
    "1006": {"status": "delivered", "items": ["t-shirt", "jeans"], "date": "2025-05-10"},
    "1007": {"status": "pending", "items": ["desk", "chair"], "date": "2025-05-22"},
    "1008": {"status": "shipped", "items": ["watch"], "date": "2025-05-16"},
    "1009": {"status": "delivered", "items": ["backpack", "notebook"], "date": "2025-05-08"},
    "1010": {"status": "pending", "items": ["printer", "ink"], "date": "2025-05-23"},
    "1011": {"status": "shipped", "items": ["tablet", "stylus"], "date": "2025-05-14"},
    "1012": {"status": "delivered", "items": ["sneakers", "socks"], "date": "2025-05-07"},
    "1013": {"status": "pending", "items": ["camera", "lens"], "date": "2025-05-24"},
    "1014": {"status": "shipped", "items": ["blender"], "date": "2025-05-13"},
    "1015": {"status": "delivered", "items": ["dress", "belt"], "date": "2025-05-06"},
    "1016": {"status": "pending", "items": ["gaming console", "controller"], "date": "2025-05-25"},
    "1017": {"status": "shipped", "items": ["microwave"], "date": "2025-05-12"},
    "1018": {"status": "delivered", "items": ["hoodie", "sweatpants"], "date": "2025-05-05"},
    "1019": {"status": "pending", "items": ["drone", "batteries"], "date": "2025-05-26"},
    "1020": {"status": "shipped", "items": ["toaster"], "date": "2025-05-11"},
    "1021": {"status": "delivered", "items": ["shirt", "tie"], "date": "2025-05-04"},
    "1022": {"status": "pending", "items": ["smartwatch", "band"], "date": "2025-05-27"},
    "1023": {"status": "shipped", "items": ["vacuum"], "date": "2025-05-10"},
    "1024": {"status": "delivered", "items": ["shorts", "sandals"], "date": "2025-05-03"},
    "1025": {"status": "pending", "items": ["earbuds", "case"], "date": "2025-05-28"},
    "1026": {"status": "shipped", "items": ["coffee maker"], "date": "2025-05-09"},
    "1027": {"status": "delivered", "items": ["jacket", "gloves"], "date": "2025-05-02"},
    "1028": {"status": "pending", "items": ["fitness tracker"], "date": "2025-05-29"},
    "1029": {"status": "shipped", "items": ["air fryer"], "date": "2025-05-08"},
    "1030": {"status": "delivered", "items": ["sweater", "scarf"], "date": "2025-05-01"},
    "1031": {"status": "pending", "items": ["external drive"], "date": "2025-05-30"},
    "1032": {"status": "shipped", "items": ["mixer"], "date": "2025-05-07"},
    "1033": {"status": "delivered", "items": ["polo", "khakis"], "date": "2025-04-30"},
    "1034": {"status": "pending", "items": ["webcam"], "date": "2025-05-31"},
    "1035": {"status": "shipped", "items": ["food processor"], "date": "2025-05-06"},
    "1036": {"status": "delivered", "items": ["raincoat", "umbrella"], "date": "2025-04-29"},
    "1037": {"status": "pending", "items": ["microphone"], "date": "2025-06-01"},
    "1038": {"status": "shipped", "items": ["slow cooker"], "date": "2025-05-05"},
    "1039": {"status": "delivered", "items": ["swimsuit", "sunglasses"], "date": "2025-04-28"},
    "1040": {"status": "pending", "items": ["router"], "date": "2025-06-02"},
    "1041": {"status": "shipped", "items": ["blender"], "date": "2025-05-04"},
    "1042": {"status": "delivered", "items": ["hat", "mittens"], "date": "2025-04-27"},
    "1043": {"status": "pending", "items": ["speakers"], "date": "2025-06-03"},
    "1044": {"status": "shipped", "items": ["juicer"], "date": "2025-05-03"},
    "1045": {"status": "delivered", "items": ["coat", "boots"], "date": "2025-04-26"},
    "1046": {"status": "pending", "items": ["projector"], "date": "2025-06-04"},
    "1047": {"status": "shipped", "items": ["rice cooker"], "date": "2025-05-02"},
    "1048": {"status": "delivered", "items": ["suit", "shoes"], "date": "2025-04-25"},
    "1049": {"status": "pending", "items": ["printer"], "date": "2025-06-05"},
    "1050": {"status": "shipped", "items": ["electric kettle"], "date": "2025-05-01"},
    "1051": {"status": "delivered", "items": ["leggings", "sports bra"], "date": "2025-04-24"},
    "1052": {"status": "pending", "items": ["monitor"], "date": "2025-06-06"},
    "1053": {"status": "shipped", "items": ["waffle maker"], "date": "2025-04-30"},
    "1054": {"status": "delivered", "items": ["blouse", "skirt"], "date": "2025-04-23"},
    "1055": {"status": "pending", "items": ["keyboard"], "date": "2025-06-07"},
    "1056": {"status": "shipped", "items": ["panini press"], "date": "2025-04-29"},
    "1057": {"status": "delivered", "items": ["vest", "tie"], "date": "2025-04-22"},
    "1058": {"status": "pending", "items": ["mouse"], "date": "2025-06-08"},
    "1059": {"status": "shipped", "items": ["pressure cooker"], "date": "2025-04-28"},
    "1060": {"status": "delivered", "items": ["cardigan", "slacks"], "date": "2025-04-21"},
    "1061": {"status": "pending", "items": ["laptop"], "date": "2025-06-09"},
    "1062": {"status": "shipped", "items": ["ice cream maker"], "date": "2025-04-27"},
    "1063": {"status": "delivered", "items": ["tank top", "shorts"], "date": "2025-04-20"},
    "1064": {"status": "pending", "items": ["tablet"], "date": "2025-06-10"},
    "1065": {"status": "shipped", "items": ["bread machine"], "date": "2025-04-26"},
    "1066": {"status": "delivered", "items": ["windbreaker", "cap"], "date": "2025-04-19"},
    "1067": {"status": "pending", "items": ["smartphone"], "date": "2025-06-11"},
    "1068": {"status": "shipped", "items": ["deep fryer"], "date": "2025-04-25"},
    "1069": {"status": "delivered", "items": ["romper"], "date": "2025-04-18"},
    "1070": {"status": "pending", "items": ["headphones"], "date": "2025-06-12"},
    "1071": {"status": "shipped", "items": ["soda maker"], "date": "2025-04-24"},
    "1072": {"status": "delivered", "items": ["jumpsuit"], "date": "2025-04-17"},
    "1073": {"status": "pending", "items": ["camera"], "date": "2025-06-13"},
    "1074": {"status": "shipped", "items": ["popcorn maker"], "date": "2025-04-23"},
    "1075": {"status": "delivered", "items": ["kimono"], "date": "2025-04-16"},
    "1076": {"status": "pending", "items": ["drone"], "date": "2025-06-14"},
    "1077": {"status": "shipped", "items": ["cotton candy machine"], "date": "2025-04-22"},
    "1078": {"status": "delivered", "items": ["poncho"], "date": "2025-04-15"},
    "1079": {"status": "pending", "items": ["gaming console"], "date": "2025-06-15"},
    "1080": {"status": "shipped", "items": ["hot dog roller"], "date": "2025-04-21"},
    "1081": {"status": "delivered", "items": ["sarong"], "date": "2025-04-14"},
    "1082": {"status": "pending", "items": ["smartwatch"], "date": "2025-06-16"},
    "1083": {"status": "shipped", "items": ["pretzel maker"], "date": "2025-04-20"},
    "1084": {"status": "delivered", "items": ["caftan"], "date": "2025-04-13"},
    "1085": {"status": "pending", "items": ["fitness tracker"], "date": "2025-06-17"},
    "1086": {"status": "shipped", "items": ["donut maker"], "date": "2025-04-19"},
    "1087": {"status": "delivered", "items": ["peacoat"], "date": "2025-04-12"},
    "1088": {"status": "pending", "items": ["earbuds"], "date": "2025-06-18"},
    "1089": {"status": "shipped", "items": ["pizza oven"], "date": "2025-04-18"},
    "1090": {"status": "delivered", "items": ["trench coat"], "date": "2025-04-11"},
    "1091": {"status": "pending", "items": ["external drive"], "date": "2025-06-19"},
    "1092": {"status": "shipped", "items": ["crepe maker"], "date": "2025-04-17"},
    "1093": {"status": "delivered", "items": ["parka"], "date": "2025-04-10"},
    "1094": {"status": "pending", "items": ["webcam"], "date": "2025-06-20"},
    "1095": {"status": "shipped", "items": ["wok"], "date": "2025-04-16"},
    "1096": {"status": "delivered", "items": ["duffle coat"], "date": "2025-04-09"},
    "1097": {"status": "pending", "items": ["microphone"], "date": "2025-06-21"},
    "1098": {"status": "shipped", "items": ["fondue set"], "date": "2025-04-15"},
    "1099": {"status": "delivered", "items": ["bomber jacket"], "date": "2025-04-08"},
    "1100": {"status": "pending", "items": ["router"], "date": "2025-06-22"},
    "1101": {"status": "shipped", "items": ["steak knives"], "date": "2025-04-14"},
    "1102": {"status": "delivered", "items": ["denim jacket"], "date": "2025-04-07"},
    "1103": {"status": "pending", "items": ["speakers"], "date": "2025-06-23"},
    "1104": {"status": "shipped", "items": ["cheese board"], "date": "2025-04-13"},
    "1105": {"status": "delivered", "items": ["leather jacket"], "date": "2025-04-06"},
    "1106": {"status": "pending", "items": ["projector"], "date": "2025-06-24"},
    "1107": {"status": "shipped", "items": ["wine glasses"], "date": "2025-04-12"},
    "1108": {"status": "delivered", "items": ["quilted jacket"], "date": "2025-04-05"},
    "1109": {"status": "pending", "items": ["monitor"], "date": "2025-06-25"},
    "1110": {"status": "shipped", "items": ["cocktail shaker"], "date": "2025-04-11"},
    "1111": {"status": "delivered", "items": ["field jacket"], "date": "2025-04-04"},
    "1112": {"status": "pending", "items": ["keyboard"], "date": "2025-06-26"},
    "1113": {"status": "shipped", "items": ["martini glasses"], "date": "2025-04-10"},
    "1114": {"status": "delivered", "items": ["harrington jacket"], "date": "2025-04-03"},
    "1115": {"status": "pending", "items": ["mouse"], "date": "2025-06-27"},
    "1116": {"status": "shipped", "items": ["whiskey stones"], "date": "2025-04-09"},
    "1117": {"status": "delivered", "items": ["anorak"], "date": "2025-04-02"},
    "1118": {"status": "pending", "items": ["laptop"], "date": "2025-06-28"},
    "1119": {"status": "shipped", "items": ["beer glasses"], "date": "2025-04-08"},
    "1120": {"status": "delivered", "items": ["puffer jacket"], "date": "2025-04-01"},
    "1121": {"status": "pending", "items": ["tablet"], "date": "2025-06-29"},
    "1122": {"status": "shipped", "items": ["shot glasses"], "date": "2025-04-07"},
    "1123": {"status": "delivered", "items": ["motorcycle jacket"], "date": "2025-03-31"},
    "1124": {"status": "pending", "items": ["smartphone"], "date": "2025-06-30"},
    "1125": {"status": "shipped", "items": ["coasters"], "date": "2025-04-06"},
    "1126": {"status": "delivered", "items": ["suede jacket"], "date": "2025-03-30"},
    "1127": {"status": "pending", "items": ["headphones"], "date": "2025-07-01"},
    "1128": {"status": "shipped", "items": ["napkin rings"], "date": "2025-04-05"},
    "1129": {"status": "delivered", "items": ["track jacket"], "date": "2025-03-29"},
    "1130": {"status": "pending", "items": ["camera"], "date": "2025-07-02"},
    "1131": {"status": "shipped", "items": ["placemats"], "date": "2025-04-04"},
    "1132": {"status": "delivered", "items": ["blouson jacket"], "date": "2025-03-28"},
    "1133": {"status": "pending", "items": ["drone"], "date": "2025-07-03"},
    "1134": {"status": "shipped", "items": ["tablecloth"], "date": "2025-04-03"},
    "1135": {"status": "delivered", "items": ["chore coat"], "date": "2025-03-27"},
    "1136": {"status": "pending", "items": ["gaming console"], "date": "2025-07-04"},
    "1137": {"status": "shipped", "items": ["apron"], "date": "2025-04-02"},
    "1138": {"status": "delivered", "items": ["shirt jacket"], "date": "2025-03-26"},
    "1139": {"status": "pending", "items": ["smartwatch"], "date": "2025-07-05"},
    "1140": {"status": "shipped", "items": ["oven mitts"], "date": "2025-04-01"},
    "1141": {"status": "delivered", "items": ["fleece jacket"], "date": "2025-03-25"},
    "1142": {"status": "pending", "items": ["fitness tracker"], "date": "2025-07-06"},
    "1143": {"status": "shipped", "items": ["pot holders"], "date": "2025-03-31"},
    "1144": {"status": "delivered", "items": ["down jacket"], "date": "2025-03-24"},
    "1145": {"status": "pending", "items": ["earbuds"], "date": "2025-07-07"},
    "1146": {"status": "shipped", "items": ["kitchen towels"], "date": "2025-03-30"},
    "1147": {"status": "delivered", "items": ["ski jacket"], "date": "2025-03-23"},
    "1148": {"status": "pending", "items": ["external drive"], "date": "2025-07-08"},
    "1149": {"status": "shipped", "items": ["cutting board"], "date": "2025-03-29"},
    "1150": {"status": "delivered", "items": ["windbreaker"], "date": "2025-03-22"}
}

products = {
    "1": {"name": "Laptop", "category": "electronics", "price": 999.99, "stock": 10},
    "2": {"name": "Mouse", "category": "electronics", "price": 29.99, "stock": 50},
    "3": {"name": "Jacket", "category": "clothing", "price": 79.99, "stock": 20},
    "4": {"name": "Monitor", "category": "electronics", "price": 199.99, "stock": 15},
    "5": {"name": "Keyboard", "category": "electronics", "price": 59.99, "stock": 30},
    "6": {"name": "Smartphone", "category": "electronics", "price": 699.99, "stock": 25},
    "7": {"name": "Headphones", "category": "electronics", "price": 149.99, "stock": 40},
    "8": {"name": "Charger", "category": "electronics", "price": 19.99, "stock": 100},
    "9": {"name": "T-shirt", "category": "clothing", "price": 24.99, "stock": 75},
    "10": {"name": "Jeans", "category": "clothing", "price": 49.99, "stock": 60},
    "11": {"name": "Desk", "category": "furniture", "price": 199.99, "stock": 8},
    "12": {"name": "Chair", "category": "furniture", "price": 129.99, "stock": 12},
    "13": {"name": "Watch", "category": "accessories", "price": 199.99, "stock": 18},
    "14": {"name": "Backpack", "category": "accessories", "price": 49.99, "stock": 35},
    "15": {"name": "Notebook", "category": "stationery", "price": 9.99, "stock": 120},
    "16": {"name": "Printer", "category": "electronics", "price": 129.99, "stock": 7},
    "17": {"name": "Ink", "category": "electronics", "price": 39.99, "stock": 45},
    "18": {"name": "Tablet", "category": "electronics", "price": 349.99, "stock": 15},
    "19": {"name": "Stylus", "category": "electronics", "price": 29.99, "stock": 60},
    "20": {"name": "Sneakers", "category": "footwear", "price": 89.99, "stock": 25},
    "21": {"name": "Socks", "category": "clothing", "price": 12.99, "stock": 200},
    "22": {"name": "Camera", "category": "electronics", "price": 599.99, "stock": 5},
    "23": {"name": "Lens", "category": "electronics", "price": 299.99, "stock": 8},
    "24": {"name": "Blender", "category": "appliances", "price": 79.99, "stock": 12},
    "25": {"name": "Dress", "category": "clothing", "price": 59.99, "stock": 30},
    "26": {"name": "Belt", "category": "accessories", "price": 29.99, "stock": 50},
    "27": {"name": "Gaming Console", "category": "electronics", "price": 499.99, "stock": 6},
    "28": {"name": "Controller", "category": "electronics", "price": 59.99, "stock": 20},
    "29": {"name": "Microwave", "category": "appliances", "price": 129.99, "stock": 10},
    "30": {"name": "Hoodie", "category": "clothing", "price": 39.99, "stock": 40},
    "31": {"name": "Sweatpants", "category": "clothing", "price": 34.99, "stock": 45},
    "32": {"name": "Drone", "category": "electronics", "price": 299.99, "stock": 4},
    "33": {"name": "Batteries", "category": "electronics", "price": 14.99, "stock": 150},
    "34": {"name": "Toaster", "category": "appliances", "price": 49.99, "stock": 15},
    "35": {"name": "Shirt", "category": "clothing", "price": 29.99, "stock": 60},
    "36": {"name": "Tie", "category": "accessories", "price": 24.99, "stock": 70},
    "37": {"name": "Smartwatch", "category": "electronics", "price": 249.99, "stock": 8},
    "38": {"name": "Band", "category": "electronics", "price": 19.99, "stock": 50},
    "39": {"name": "Vacuum", "category": "appliances", "price": 199.99, "stock": 7},
    "40": {"name": "Shorts", "category": "clothing", "price": 34.99, "stock": 55},
    "41": {"name": "Sandals", "category": "footwear", "price": 39.99, "stock": 30},
    "42": {"name": "Earbuds", "category": "electronics", "price": 129.99, "stock": 25},
    "43": {"name": "Case", "category": "electronics", "price": 19.99, "stock": 80},
    "44": {"name": "Coffee Maker", "category": "appliances", "price": 89.99, "stock": 12},
    "45": {"name": "Gloves", "category": "clothing", "price": 19.99, "stock": 65},
    "46": {"name": "Fitness Tracker", "category": "electronics", "price": 99.99, "stock": 15},
    "47": {"name": "Air Fryer", "category": "appliances", "price": 119.99, "stock": 9},
    "48": {"name": "Sweater", "category": "clothing", "price": 44.99, "stock": 35},
    "49": {"name": "Scarf", "category": "accessories", "price": 24.99, "stock": 75},
    "50": {"name": "External Drive", "category": "electronics", "price": 89.99, "stock": 20},
    "51": {"name": "Mixer", "category": "appliances", "price": 149.99, "stock": 6},
    "52": {"name": "Polo", "category": "clothing", "price": 34.99, "stock": 50},
    "53": {"name": "Khakis", "category": "clothing", "price": 49.99, "stock": 40},
    "54": {"name": "Webcam", "category": "electronics", "price": 69.99, "stock": 25},
    "55": {"name": "Food Processor", "category": "appliances", "price": 129.99, "stock": 7},
    "56": {"name": "Raincoat", "category": "clothing", "price": 59.99, "stock": 20},
    "57": {"name": "Umbrella", "category": "accessories", "price": 19.99, "stock": 90},
    "58": {"name": "Microphone", "category": "electronics", "price": 99.99, "stock": 12},
    "59": {"name": "Slow Cooker", "category": "appliances", "price": 79.99, "stock": 10},
    "60": {"name": "Swimsuit", "category": "clothing", "price": 39.99, "stock": 30},
    "61": {"name": "Sunglasses", "category": "accessories", "price": 129.99, "stock": 25},
    "62": {"name": "Router", "category": "electronics", "price": 89.99, "stock": 15},
    "63": {"name": "Juicer", "category": "appliances", "price": 59.99, "stock": 12},
    "64": {"name": "Coat", "category": "clothing", "price": 99.99, "stock": 15},
    "65": {"name": "Boots", "category": "footwear", "price": 119.99, "stock": 12},
    "66": {"name": "Projector", "category": "electronics", "price": 299.99, "stock": 5},
    "67": {"name": "Rice Cooker", "category": "appliances", "price": 49.99, "stock": 14},
    "68": {"name": "Suit", "category": "clothing", "price": 199.99, "stock": 8},
    "69": {"name": "Shoes", "category": "footwear", "price": 89.99, "stock": 20},
    "70": {"name": "Electric Kettle", "category": "appliances", "price": 39.99, "stock": 18},
    "71": {"name": "Leggings", "category": "clothing", "price": 29.99, "stock": 60},
    "72": {"name": "Sports Bra", "category": "clothing", "price": 34.99, "stock": 45},
    "73": {"name": "Waffle Maker", "category": "appliances", "price": 29.99, "stock": 20},
    "74": {"name": "Blouse", "category": "clothing", "price": 39.99, "stock": 40},
    "75": {"name": "Skirt", "category": "clothing", "price": 34.99, "stock": 35},
    "76": {"name": "Panini Press", "category": "appliances", "price": 49.99, "stock": 12},
    "77": {"name": "Vest", "category": "clothing", "price": 44.99, "stock": 25},
    "78": {"name": "Pressure Cooker", "category": "appliances", "price": 119.99, "stock": 7},
    "79": {"name": "Cardigan", "category": "clothing", "price": 49.99, "stock": 30},
    "80": {"name": "Slacks", "category": "clothing", "price": 54.99, "stock": 25},
    "81": {"name": "Ice Cream Maker", "category": "appliances", "price": 79.99, "stock": 8},
    "82": {"name": "Tank Top", "category": "clothing", "price": 19.99, "stock": 80},
    "83": {"name": "Bread Machine", "category": "appliances", "price": 129.99, "stock": 5},
    "84": {"name": "Windbreaker", "category": "clothing", "price": 59.99, "stock": 20},
    "85": {"name": "Cap", "category": "accessories", "price": 24.99, "stock": 70},
    "86": {"name": "Deep Fryer", "category": "appliances", "price": 89.99, "stock": 6},
    "87": {"name": "Romper", "category": "clothing", "price": 39.99, "stock": 25},
    "88": {"name": "Soda Maker", "category": "appliances", "price": 99.99, "stock": 7},
    "89": {"name": "Jumpsuit", "category": "clothing", "price": 49.99, "stock": 20},
    "90": {"name": "Popcorn Maker", "category": "appliances", "price": 49.99, "stock": 10},
    "91": {"name": "Kimono", "category": "clothing", "price": 69.99, "stock": 15},
    "92": {"name": "Cotton Candy Machine", "category": "appliances", "price": 59.99, "stock": 4},
    "93": {"name": "Poncho", "category": "clothing", "price": 44.99, "stock": 20},
    "94": {"name": "Hot Dog Roller", "category": "appliances", "price": 199.99, "stock": 3},
    "95": {"name": "Sarong", "category": "clothing", "price": 29.99, "stock": 35},
    "96": {"name": "Pretzel Maker", "category": "appliances", "price": 79.99, "stock": 5},
    "97": {"name": "Caftan", "category": "clothing", "price": 59.99, "stock": 15},
    "98": {"name": "Donut Maker", "category": "appliances", "price": 39.99, "stock": 8},
    "99": {"name": "Peacoat", "category": "clothing", "price": 129.99, "stock": 10},
    "100": {"name": "Pizza Oven", "category": "appliances", "price": 149.99, "stock": 4},
    "101": {"name": "Trench Coat", "category": "clothing", "price": 149.99, "stock": 8},
    "102": {"name": "Crepe Maker", "category": "appliances", "price": 49.99, "stock": 7},
    "103": {"name": "Parka", "category": "clothing", "price": 179.99, "stock": 6},
    "104": {"name": "Wok", "category": "appliances", "price": 39.99, "stock": 15},
    "105": {"name": "Duffle Coat", "category": "clothing", "price": 119.99, "stock": 9},
    "106": {"name": "Fondue Set", "category": "appliances", "price": 79.99, "stock": 6},
    "107": {"name": "Bomber Jacket", "category": "clothing", "price": 99.99, "stock": 12},
    "108": {"name": "Steak Knives", "category": "kitchen", "price": 49.99, "stock":4},
    "93": {"name": "Poncho", "category": "clothing", "price": 44.99, "stock": 20},
    "94": {"name": "Hot Dog Roller", "category": "appliances", "price": 199.99, "stock": 3},
    "95": {"name": "Sarong", "category": "clothing", "price": 29.99, "stock": 35},
    "96": {"name": "Pretzel Maker", "category": "appliances", "price": 79.99, "stock": 5},
    "97": {"name": "Caftan", "category": "clothing", "price": 59.99, "stock": 15},
    "98": {"name": "Donut Maker", "category": "appliances", "price": 39.99, "stock": 8},
    "99": {"name": "Peacoat", "category": "clothing", "price": 129.99, "stock": 10},
    "100": {"name": "Pizza Oven", "category": "appliances", "price": 149.99, "stock": 4},
    "101": {"name": "Trench Coat", "category": "clothing", "price": 149.99, "stock": 8},
    "102": {"name": "Crepe Maker", "category": "appliances", "price": 49.99, "stock": 7},
    "103": {"name": "Parka", "category": "clothing", "price": 179.99, "stock": 6},
    "104": {"name": "Wok", "category": "appliances", "price": 39.99, "stock": 15},
    "105": {"name": "Duffle Coat", "category": "clothing", "price": 119.99, "stock": 9},
    "106": {"name": "Fondue Set", "category": "appliances", "price": 79.99, "stock": 6},
    "107": {"name": "Bomber Jacket", "category": "clothing", "price": 99.99, "stock": 12},
    "108": {"name": "Steak Knives", "category": "kitchen", "price": 49.99, "stock":14},
    "109": {"name": "Denim Jacket", "category": "clothing", "price": 69.99, "stock": 18},
    "110": {"name": "Cheese Board", "category": "kitchen", "price": 39.99, "stock": 25},
    "111": {"name": "Leather Jacket", "category": "clothing", "price": 199.99, "stock": 5},
    "112": {"name": "Wine Glasses", "category": "kitchen", "price": 29.99, "stock": 40},
    "113": {"name": "Quilted Jacket", "category": "clothing", "price": 89.99, "stock": 15},
    "114": {"name": "Cocktail Shaker", "category": "kitchen", "price": 19.99, "stock": 50},
    "115": {"name": "Field Jacket", "category": "clothing", "price": 79.99, "stock": 12},
    "116": {"name": "Martini Glasses", "category": "kitchen", "price": 24.99, "stock": 45},
    "117": {"name": "Harrington Jacket", "category": "clothing", "price": 69.99, "stock": 14},
    "118": {"name": "Whiskey Stones", "category": "kitchen", "price": 14.99, "stock": 80},
    "119": {"name": "Anorak", "category": "clothing", "price": 59.99, "stock": 16},
    "120": {"name": "Beer Glasses", "category": "kitchen", "price": 19.99, "stock": 60},
    "121": {"name": "Puffer Jacket", "category": "clothing", "price": 129.99, "stock": 10},
    "122": {"name": "Shot Glasses", "category": "kitchen", "price": 9.99, "stock": 150},
    "123": {"name": "Motorcycle Jacket", "category": "clothing", "price": 179.99, "stock": 7},
    "124": {"name": "Coasters", "category": "kitchen", "price": 12.99, "stock": 100},
    "125": {"name": "Suede Jacket", "category": "clothing", "price": 149.99, "stock": 8},
    "126": {"name": "Napkin Rings", "category": "kitchen", "price": 14.99, "stock": 80},
    "127": {"name": "Track Jacket", "category": "clothing", "price": 49.99, "stock": 20},
    "128": {"name": "Placemats", "category": "kitchen", "price": 19.99, "stock": 70},
    "129": {"name": "Blouson Jacket", "category": "clothing", "price": 79.99, "stock": 12},
    "130": {"name": "Tablecloth", "category": "kitchen", "price": 29.99, "stock": 40},
    "131": {"name": "Chore Coat", "category": "clothing", "price": 59.99, "stock": 15},
    "132": {"name": "Apron", "category": "kitchen", "price": 24.99, "stock": 60},
    "133": {"name": "Shirt Jacket", "category": "clothing", "price": 69.99, "stock": 14},
    "134": {"name": "Oven Mitts", "category": "kitchen", "price": 14.99, "stock": 90},
    "135": {"name": "Fleece Jacket", "category": "clothing", "price": 49.99, "stock": 18},
    "136": {"name": "Pot Holders", "category": "kitchen", "price": 9.99, "stock": 120},
    "137": {"name": "Down Jacket", "category": "clothing", "price": 149.99, "stock": 9},
    "138": {"name": "Kitchen Towels", "category": "kitchen", "price": 12.99, "stock": 100},
    "139": {"name": "Ski Jacket", "category": "clothing", "price": 199.99, "stock": 6},
    "140": {"name": "Cutting Board", "category": "kitchen", "price": 19.99, "stock": 50},
    "141": {"name": "Windbreaker", "category": "clothing", "price": 59.99, "stock": 20},
    "142": {"name": "Measuring Cups", "category": "kitchen", "price": 14.99, "stock": 80},
    "143": {"name": "Rain Jacket", "category": "clothing", "price": 79.99, "stock": 12},
    "144": {"name": "Mixing Bowls", "category": "kitchen", "price": 24.99, "stock": 60},
    "145": {"name": "Winter Coat", "category": "clothing", "price": 129.99, "stock": 10},
    "146": {"name": "Colander", "category": "kitchen", "price": 12.99, "stock": 70},
    "147": {"name": "Parka", "category": "clothing", "price": 149.99, "stock": 8},
    "148": {"name": "Grater", "category": "kitchen", "price": 9.99, "stock": 100},
    "149": {"name": "Quilted Jacket", "category": "clothing", "price": 89.99, "stock": 15},
    "150": {"name": "Peeler", "category": "kitchen", "price": 7.99, "stock": 150}
}

customers = {
    "C001": {"name": "John Doe", "preferences": ["electronics"], "loyalty_points": 100},
    "C002": {"name": "Jane Smith", "preferences": ["clothing"], "loyalty_points": 50},
    "C003": {"name": "Robert Johnson", "preferences": ["electronics", "books"], "loyalty_points": 75},
    "C004": {"name": "Emily Davis", "preferences": ["home goods"], "loyalty_points": 30},
    "C005": {"name": "Michael Brown", "preferences": ["sports"], "loyalty_points": 120},
    "C006": {"name": "Sarah Wilson", "preferences": ["clothing", "beauty"], "loyalty_points": 65},
    "C007": {"name": "David Taylor", "preferences": ["electronics", "gaming"], "loyalty_points": 200},
    "C008": {"name": "Jessica Anderson", "preferences": ["home decor"], "loyalty_points": 45},
    "C009": {"name": "Thomas Martinez", "preferences": ["tools", "automotive"], "loyalty_points": 85},
    "C010": {"name": "Jennifer Robinson", "preferences": ["clothing", "accessories"], "loyalty_points": 55},
    "C011": {"name": "William Clark", "preferences": ["electronics", "photography"], "loyalty_points": 110},
    "C012": {"name": "Lisa Rodriguez", "preferences": ["jewelry"], "loyalty_points": 95},
    "C013": {"name": "James Lewis", "preferences": ["outdoors"], "loyalty_points": 70},
    "C014": {"name": "Mary Walker", "preferences": ["kitchen"], "loyalty_points": 40},
    "C015": {"name": "Daniel Hall", "preferences": ["music"], "loyalty_points": 60},
    "C016": {"name": "Patricia Young", "preferences": ["fitness"], "loyalty_points": 80},
    "C017": {"name": "Christopher Allen", "preferences": ["tech"], "loyalty_points": 150},
    "C018": {"name": "Linda King", "preferences": ["crafts"], "loyalty_points": 35},
    "C019": {"name": "Matthew Wright", "preferences": ["collectibles"], "loyalty_points": 25},
    "C020": {"name": "Barbara Scott", "preferences": ["pet supplies"], "loyalty_points": 55},
    "C021": {"name": "Donald Green", "preferences": ["office"], "loyalty_points": 45},
    "C022": {"name": "Elizabeth Adams", "preferences": ["baby"], "loyalty_points": 75},
    "C023": {"name": "Richard Baker", "preferences": ["gardening"], "loyalty_points": 50},
    "C024": {"name": "Susan Nelson", "preferences": ["art"], "loyalty_points": 65},
    "C025": {"name": "Joseph Carter", "preferences": ["travel"], "loyalty_points": 90},
    "C026": {"name": "Nancy Mitchell", "preferences": ["furniture"], "loyalty_points": 30},
    "C027": {"name": "Charles Perez", "preferences": ["auto"], "loyalty_points": 85},
    "C028": {"name": "Karen Roberts", "preferences": ["party supplies"], "loyalty_points": 20},
    "C029": {"name": "Thomas Turner", "preferences": ["movies"], "loyalty_points": 40},
    "C030": {"name": "Betty Phillips", "preferences": ["books"], "loyalty_points": 60},
    "C031": {"name": "Steven Campbell", "preferences": ["board games"], "loyalty_points": 35},
    "C032": {"name": "Dorothy Parker", "preferences": ["bath"], "loyalty_points": 45},
    "C033": {"name": "Anthony Evans", "preferences": ["shoes"], "loyalty_points": 70},
    "C034": {"name": "Sandra Edwards", "preferences": ["handbags"], "loyalty_points": 95},
    "C035": {"name": "Kenneth Collins", "preferences": ["tools"], "loyalty_points": 55},
    "C036": {"name": "Carol Stewart", "preferences": ["stationery"], "loyalty_points": 25},
    "C037": {"name": "Brian Sanchez", "preferences": ["cooking"], "loyalty_points": 65},
    "C038": {"name": "Ruth Morris", "preferences": ["fishing"], "loyalty_points": 45},
    "C039": {"name": "Ronald Rogers", "preferences": ["hunting"], "loyalty_points": 30},
    "C040": {"name": "Sharon Reed", "preferences": ["yoga"], "loyalty_points": 50},
    "C041": {"name": "Edward Cook", "preferences": ["cycling"], "loyalty_points": 75},
    "C042": {"name": "Donna Morgan", "preferences": ["running"], "loyalty_points": 60},
    "C043": {"name": "Jason Bell", "preferences": ["swimming"], "loyalty_points": 40},
    "C044": {"name": "Michelle Murphy", "preferences": ["camping"], "loyalty_points": 55},
    "C045": {"name": "Jeffrey Bailey", "preferences": ["hiking"], "loyalty_points": 65},
    "C046": {"name": "Laura Rivera", "preferences": ["skiing"], "loyalty_points": 35},
    "C047": {"name": "Ryan Cooper", "preferences": ["snowboarding"], "loyalty_points": 30},
    "C048": {"name": "Deborah Richardson", "preferences": ["skateboarding"], "loyalty_points": 20},
    "C049": {"name": "Gary Cox", "preferences": ["surfing"], "loyalty_points": 25},
    "C050": {"name": "Amanda Howard", "preferences": ["golf"], "loyalty_points": 45},
    "C051": {"name": "Jacob Ward", "preferences": ["tennis"], "loyalty_points": 40},
    "C052": {"name": "Stephanie Torres", "preferences": ["basketball"], "loyalty_points": 35},
    "C053": {"name": "Kevin Peterson", "preferences": ["baseball"], "loyalty_points": 30},
    "C054": {"name": "Rebecca Gray", "preferences": ["football"], "loyalty_points": 25},
    "C055": {"name": "Timothy Ramirez", "preferences": ["soccer"], "loyalty_points": 40},
    "C056": {"name": "Shirley James", "preferences": ["hockey"], "loyalty_points": 20},
    "C057": {"name": "Frank Watson", "preferences": ["volleyball"], "loyalty_points": 15},
    "C058": {"name": "Cynthia Brooks", "preferences": ["rugby"], "loyalty_points": 10},
    "C059": {"name": "Raymond Kelly", "preferences": ["cricket"], "loyalty_points": 5},
    "C060": {"name": "Kathleen Sanders", "preferences": ["badminton"], "loyalty_points": 15},
    "C061": {"name": "Vincent Price", "preferences": ["table tennis"], "loyalty_points": 20},
    "C062": {"name": "Anna Bennett", "preferences": ["bowling"], "loyalty_points": 25},
    "C063": {"name": "Russell Wood", "preferences": ["boxing"], "loyalty_points": 10},
    "C064": {"name": "Brenda Barnes", "preferences": ["mma"], "loyalty_points": 5},
    "C065": {"name": "Philip Ross", "preferences": ["wrestling"], "loyalty_points": 5},
    "C066": {"name": "Pamela Henderson", "preferences": ["gymnastics"], "loyalty_points": 15},
    "C067": {"name": "Louis Coleman", "preferences": ["dance"], "loyalty_points": 20},
    "C068": {"name": "Emma Jenkins", "preferences": ["ballet"], "loyalty_points": 10},
    "C069": {"name": "Brandon Perry", "preferences": ["theater"], "loyalty_points": 25},
    "C070": {"name": "Janet Powell", "preferences": ["opera"], "loyalty_points": 5},
    "C071": {"name": "Eugene Long", "preferences": ["concerts"], "loyalty_points": 30},
    "C072": {"name": "Diane Hughes", "preferences": ["festivals"], "loyalty_points": 20},
    "C073": {"name": "Bruce Foster", "preferences": ["museums"], "loyalty_points": 15},
    "C074": {"name": "Alice Butler", "preferences": ["galleries"], "loyalty_points": 10},
    "C075": {"name": "Alan Simmons", "preferences": ["exhibitions"], "loyalty_points": 5},
    "C076": {"name": "Teresa Bryant", "preferences": ["lectures"], "loyalty_points": 15},
    "C077": {"name": "Samuel Russell", "preferences": ["workshops"], "loyalty_points": 20},
    "C078": {"name": "Heather Griffin", "preferences": ["seminars"], "loyalty_points": 10},
    "C079": {"name": "Patrick Diaz", "preferences": ["conferences"], "loyalty_points": 5},
    "C080": {"name": "Denise Hayes", "preferences": ["trade shows"], "loyalty_points": 15},
    "C081": {"name": "Peter Myers", "preferences": ["fairs"], "loyalty_points": 10},
    "C082": {"name": "Judith Ford", "preferences": ["markets"], "loyalty_points": 5},
    "C083": {"name": "Roger Hamilton", "preferences": ["bazaars"], "loyalty_points": 5},
    "C084": {"name": "Martha Graham", "preferences": ["auctions"], "loyalty_points": 10},
    "C085": {"name": "Johnny Wallace", "preferences": ["antiques"], "loyalty_points": 15},
    "C086": {"name": "Frances West", "preferences": ["vintage"], "loyalty_points": 20},
    "C087": {"name": "Clarence Cole", "preferences": ["retro"], "loyalty_points": 10},
    "C088": {"name": "Ann Owens", "preferences": ["collectibles"], "loyalty_points": 25},
    "C089": {"name": "Philip Fisher", "preferences": ["memorabilia"], "loyalty_points": 5},
    "C090": {"name": "Marie Mason", "preferences": ["coins"], "loyalty_points": 15},
    "C091": {"name": "Chris Dixon", "preferences": ["stamps"], "loyalty_points": 10},
    "C092": {"name": "Jean Crawford", "preferences": ["cards"], "loyalty_points": 20},
    "C093": {"name": "Earl Boyd", "preferences": ["comics"], "loyalty_points": 25},
    "C094": {"name": "Kathryn Freeman", "preferences": ["toys"], "loyalty_points": 30},
    "C095": {"name": "Jimmy Dean", "preferences": ["games"], "loyalty_points": 35},
    "C096": {"name": "Doris Spencer", "preferences": ["puzzles"], "loyalty_points": 20},
    "C097": {"name": "Arthur Gardner", "preferences": ["models"], "loyalty_points": 15},
    "C098": {"name": "Phyllis Stephens", "preferences": ["dolls"], "loyalty_points": 10},
    "C099": {"name": "Lawrence Snyder", "preferences": ["action figures"], "loyalty_points": 5},
    "C100": {"name": "Paula Tucker", "preferences": ["plush"], "loyalty_points": 15},
    "C101": {"name": "Roy Porter", "preferences": ["building sets"], "loyalty_points": 20},
    "C102": {"name": "Lois Hunter", "preferences": ["educational"], "loyalty_points": 25},
    "C103": {"name": "Walter Hicks", "preferences": ["science kits"], "loyalty_points": 15},
    "C104": {"name": "Gloria Crawford", "preferences": ["arts & crafts"], "loyalty_points": 30},
    "C105": {"name": "Wayne Henry", "preferences": ["musical instruments"], "loyalty_points": 20},
    "C106": {"name": "Theresa Boyd", "preferences": ["outdoor play"], "loyalty_points": 15},
    "C107": {"name": "Aaron Mason", "preferences": ["ride-ons"], "loyalty_points": 10},
    "C108": {"name": "Diana Morrison", "preferences": ["pretend play"], "loyalty_points": 5},
    "C109": {"name": "Bruce Ferguson", "preferences": ["dress up"], "loyalty_points": 15},
    "C110": {"name": "Beverly Hamilton", "preferences": ["baby toys"], "loyalty_points": 20},
    "C111": {"name": "Alan Woods", "preferences": ["toddler toys"], "loyalty_points": 15},
    "C112": {"name": "Norma Castillo", "preferences": ["preschool toys"], "loyalty_points": 10},
    "C113": {"name": "Harry George", "preferences": ["bath toys"], "loyalty_points": 5},
    "C114": {"name": "Lillian Schmidt", "preferences": ["soft toys"], "loyalty_points": 15},
    "C115": {"name": "Carlos Rice", "preferences": ["wooden toys"], "loyalty_points": 20},
    "C116": {"name": "Ruby Alvarez", "preferences": ["electronic toys"], "loyalty_points": 25},
    "C117": {"name": "Ralph Webb", "preferences": ["robotic toys"], "loyalty_points": 15},
    "C118": {"name": "Annie Johnston", "preferences": ["remote control"], "loyalty_points": 10},
    "C119": {"name": "Howard Nguyen", "preferences": ["drones"], "loyalty_points": 5},
    "C120": {"name": "Irene Medina", "preferences": ["vehicles"], "loyalty_points": 15},
    "C121": {"name": "Frederick Fowler", "preferences": ["trains"], "loyalty_points": 20},
    "C122": {"name": "Marion Gibson", "preferences": ["planes"], "loyalty_points": 15},
    "C123": {"name": "Evelyn Mcdonald", "preferences": ["boats"], "loyalty_points": 10},
    "C124": {"name": "Leonard Hart", "preferences": ["cars"], "loyalty_points": 5},
    "C125": {"name": "Glenda Harper", "preferences": ["trucks"], "loyalty_points": 15},
    "C126": {"name": "Martin Fuller", "preferences": ["construction"], "loyalty_points": 20},
    "C127": {"name": "Vivian Lynch", "preferences": ["farm"], "loyalty_points": 15},
    "C128": {"name": "Dean Obrien", "preferences": ["zoo"], "loyalty_points": 10},
    "C129": {"name": "Edna Vasquez", "preferences": ["dinosaurs"], "loyalty_points": 5},
    "C130": {"name": "Geraldine Bishop", "preferences": ["animals"], "loyalty_points": 15},
    "C131": {"name": "Keith Carroll", "preferences": ["pets"], "loyalty_points": 20},
    "C132": {"name": "Bernice Garrett", "preferences": ["sea creatures"], "loyalty_points": 15},
    "C133": {"name": "Roger Welch", "preferences": ["insects"], "loyalty_points": 10},
    "C134": {"name": "Florence Oliver", "preferences": ["birds"], "loyalty_points": 5},
    "C135": {"name": "Lee Gregory", "preferences": ["reptiles"], "loyalty_points": 15},
    "C136": {"name": "Yvonne Silva", "preferences": ["jungle"], "loyalty_points": 20},
    "C137": {"name": "Benjamin Vargas", "preferences": ["forest"], "loyalty_points": 15},
    "C138": {"name": "Lillie Blake", "preferences": ["arctic"], "loyalty_points": 10},
    "C139": {"name": "Alfredo Guzman", "preferences": ["desert"], "loyalty_points": 5},
    "C140": {"name": "Kristina Swanson", "preferences": ["ocean"], "loyalty_points": 15},
    "C141": {"name": "Clifton Herrera", "preferences": ["space"], "loyalty_points": 20},
    "C142": {"name": "Nina Cohen", "preferences": ["fantasy"], "loyalty_points": 15},
    "C143": {"name": "Leroy Douglas", "preferences": ["adventure"], "loyalty_points": 10},
    "C144": {"name": "Marguerite Brewer", "preferences": ["superheroes"], "loyalty_points": 5},
    "C145": {"name": "Dwayne Mann", "preferences": ["princesses"], "loyalty_points": 15},
    "C146": {"name": "Lynne Marsh", "preferences": ["fairies"], "loyalty_points": 20},
    "C147": {"name": "Oscar Vaughn", "preferences": ["pirates"], "loyalty_points": 15},
    "C148": {"name": "Elsie Erickson", "preferences": ["cowboys"], "loyalty_points": 10},
    "C149": {"name": "Kirk Spencer", "preferences": ["knights"], "loyalty_points": 5},
    "C150": {"name": "Miriam Wheeler", "preferences": ["dragons"], "loyalty_points": 15}
}

def get_order(order_id):
    """Retrieve order details by ID."""
    return orders.get(order_id, {"error": "Order not found"})

def update_order(order_id, status):
    """Update order status with business rules."""
    if order_id in orders and orders[order_id]["status"] == "pending":
        orders[order_id]["status"] = status
        return {"success": f"Order {order_id} updated to {status}"}
    return {"error": "Cannot update order"}

def get_product(product_id):
    """Retrieve product details by ID."""
    return products.get(product_id, {"error": "Product not found"})

def search_products(query):
    """Search products by name or category."""
    return [p for p in products.values() if query.lower() in p["name"].lower() or query.lower() in p["category"].lower()]

def get_customer(customer_id):
    """Retrieve customer details by ID."""
    return customers.get(customer_id, {"error": "Customer not found"})

def update_customer_preferences(customer_id, preference):
    """Update customer preferences."""
    if customer_id in customers:
        customers[customer_id]["preferences"].append(preference)
        return {"success": f"Preferences updated for {customer_id}"}
    return {"error": "Customer not found"}

def get_loyalty_points(customer_id):
    """Retrieve customer loyalty points."""
    return customers.get(customer_id, {"error": "Customer not found"})["loyalty_points"]
